export const ExampleArticles = [
  {
    title: "How influential is Elon Musk on the crypto market?",
    author: "Pip Murrison",
    published_date: "2021-09-13 21:40:22",
    published_date_precision: "full",
    link: "https://www.express.co.uk/finance/city/1490736/elon-musk-crypto-market-bitcoin-cryptocurrencies-evg",
    clean_url: "express.co.uk",
    summary:
      "Elon Musk is well known for airing his views on social media. With more than 59.8 million Twitter followers, this entrepreneur has a huge platform to share his views. His tweets on cryptocurrencies have caused the markets to skyrocket or plummet in the past.Elon Musk is the infamous boss of Tesla and co-founder of SpaceX.The billionaire entrepreneur is no stranger to social media as his regular posts are lapped up by his fans.And Mr Musk's latest tweet has sent prices of cryptos soaring once aga",
    rights: "express.co.uk",
    rank: 548,
    topic: "finance",
    country: "GB",
    language: "en",
    authors: ["Pip Murrison"],
    media:
      "https://cdn.images.express.co.uk/img/dynamic/22/750x445/1490736.jpg",
    is_opinion: false,
    twitter_account: null,
    _score: 26.451103,
    _id: "c1939332e3529d4ef567615f99bdc59a",
  },
  {
    title:
      "What is known about Ad Astra, the mysterious disruptive school created by Elon Musk where his children study?",
    author: "Mairem Del Río",
    published_date: "2021-09-13 14:00:00",
    published_date_precision: "timezone unknown",
    link: "https://www.entrepreneur.com/article/385257",
    clean_url: "entrepreneur.com",
    summary:
      "This article was translated from our Spanish edition. Opinions expressed by Entrepreneur contributors are their own. Genius, millionaire, playboy , philanthropist, Tesla techno-king , emperor of Mars … and promoter of alternative education methods. Elon Musk has criticized America's educational system on several occasions, but instead of just making complaints, he got down to business. In 2014, the billionaire announced the creation of Ad Astra , a mysterious disruptive school with its own syste",
    rights: "entrepreneur.com",
    rank: 362,
    topic: "news",
    country: "unknown",
    language: "en",
    authors: ["Mairem Del Río"],
    media:
      "https://assets.entrepreneur.com/content/3x2/2000/1631475261-Sep13ElonMuskAdAstraescuelaalternativametodosistemainscripciones.jpeg",
    is_opinion: false,
    twitter_account: "@Entrepreneur",
    _score: 24.124779,
    _id: "c7e31aeeae15b3b449e1356c9d87a37c",
  },
  {
    title: "On Jack Dorsey's Tweet, Elon Musk Says It's His 'Safe' Word Too",
    author: null,
    published_date: "2021-09-17 05:00:06",
    published_date_precision: "full",
    link: "https://www.ndtv.com/business/elon-musk-responds-to-jack-dorsey-s-cryptic-one-word-tweet-2543827",
    clean_url: "ndtv.com",
    summary:
      'The Twitter CEO just said "crypto", suggesting he preferred the usage over "currency"It\'s no secret that Tesla and SpaceX boss Elon Musk and Twitter CEO Jack Dorsey support cryptocurrency over the traditional \'fiat\' money. But their bromance is now more and more apparent on public platforms. Recently, they discussed the future of Bitcoin at a virtual conference, praising its potential to change the monetary systems. And now Mr Musk has replied to a cryptic one-word tweet by Dorsey. The Twitter C',
    rights: "google.com",
    rank: 895,
    topic: "news",
    country: "IN",
    language: "en",
    authors: [],
    media:
      "https://c.ndtvimg.com/2021-08/0deakdik_elon-musk_625x300_12_August_21.jpg",
    is_opinion: false,
    twitter_account: "@ndtv",
    _score: 24.239088,
    _id: "34a16ca57967b0a3e12fcaa68618a354",
  },
];
